# Form implementation generated from reading ui file 'World_time_help.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Help_Window(object):
    def setupUi(self, Help_Window):
        Help_Window.setObjectName("Help_Window")
        Help_Window.resize(925, 806)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/kworldclock.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Help_Window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=Help_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(254, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pushB_Close = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushB_Close.setFont(font)
        self.pushB_Close.setObjectName("pushB_Close")
        self.gridLayout.addWidget(self.pushB_Close, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(254, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        Help_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Help_Window)
        self.pushB_Close.clicked.connect(Help_Window.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Help_Window)

    def retranslateUi(self, Help_Window):
        _translate = QtCore.QCoreApplication.translate
        Help_Window.setWindowTitle(_translate("Help_Window", "Помощь к игре \"Морской бой\""))
        self.pushB_Close.setText(_translate("Help_Window", "Закрыть"))
